export const Students1 = [
  {
    id: 1,
    name: "John Doe",
    lastname: "Doe",
    status: "bad",
    details: {
      age: 20,
      email: "example@gmail.com",
      phone: "1234567890",
      address: "1234 Main St",
      city: "City",
      state: "State",
      zip: "12345",
    },
  },
  {
    id: 2,
    name: "John Doe",
    lastname: "Doe",
    status: "good",
    details: {
      age: 20,
      email: "example@gmail.com",
      phone: "1234567890",
      address: "1234 Main St",
      city: "City",
      state: "State",
      zip: "12345",
    },
  },
  {
    id: 3,
    name: "John Doe",
    lastname: "Doe",
    status: "medium",
    details: {
      age: 20,
      email: "example@gmail.com",
      phone: "1234567890",
      address: "1234 Main St",
      city: "City",
      state: "State",
      zip: "12345",
    },
  },
];

export const Students2 = [
  {
    id: 1,
    name: "John Doe",
    lastname: "Doe",
    status: "bad",
    details: {
      age: 20,
      email: "example@gmail.com",
      phone: "1234567890",
      address: "1234 Main St",
      city: "City",
      state: "State",
      zip: "12345",
    },
  },
  {
    id: 2,
    name: "John Doe",
    lastname: "Doe",
    status: "good",
    details: {
      age: 20,
      email: "example@gmail.com",
      phone: "1234567890",
      address: "1234 Main St",
      city: "City",
      state: "State",
      zip: "12345",
    },
  },
];
