export const Students1 = [
  {
    id: 1,
    name: "Abelardo",
    lastname: "Doe",
    status: 4,
    details: {
      age: 20,
      email: "example@gmail.com",
      phone: "1234567890",
      address: "1234 Main St",
      city: "City",
      state: "State",
      zip: "12345",
    },
  },
  {
    id: 1,
    name: "Angel",
    lastname: "Doe",
    status: 4,
    details: {
      age: 20,
      email: "example@gmail.com",
      phone: "1234567890",
      address: "1234 Main St",
      city: "City",
      state: "State",
      zip: "12345",
    },
  },
  {
    id: 2,
    name: "Luis",
    lastname: "Doe",
    status: 8,
    details: {
      age: 20,
      email: "example@gmail.com",
      phone: "1234567890",
      address: "1234 Main St",
      city: "City",
      state: "State",
      zip: "12345",
    },
  },
  {
    id: 3,
    name: "Ricardo",
    lastname: "Doe",
    status: 6,
    details: {
      age: 20,
      email: "example@gmail.com",
      phone: "1234567890",
      address: "1234 Main St",
      city: "City",
      state: "State",
      zip: "12345",
    },
  },
];

export const Students2 = [
  {
    id: 1,
    name: "John Doe",
    lastname: "Doe",
    status: 2,
    details: {
      age: 20,
      email: "example@gmail.com",
      phone: "1234567890",
      address: "1234 Main St",
      city: "City",
      state: "State",
      zip: "12345",
    },
  },
  {
    id: 2,
    name: "John Doe",
    lastname: "Doe",
    status: 9,
    details: {
      age: 20,
      email: "example@gmail.com",
      phone: "1234567890",
      address: "1234 Main St",
      city: "City",
      state: "State",
      zip: "12345",
    },
  },
];
