import { Students1, Students2 } from "./Students";
export const subjects = [
  {
    id: 1,
    name: "Math",
    teacher: "John Doe",
    group_id: 1,
    students: Students1,
  },
  {
    id: 2,
    name: "Science",
    teacher: "Jane Doe",
    group_id: 1,
    students: Students2,
  },
  {
    id: 3,
    name: "History",
    teacher: "John Doe",
    group_id: 1,
    students: Students1,
  },
  {
    id: 4,
    name: "English",
    teacher: "Jane Doe",
    group_id: 1,
    students: Students2,
  },
  {
    id: 1,
    name: "Math",
    teacher: "John Doe",
    group_id: 1,
    students: Students1,
  },
  {
    id: 2,
    name: "Science",
    teacher: "Jane Doe",
    group_id: 1,
    students: Students2,
  },
  {
    id: 3,
    name: "History",
    teacher: "John Doe",
    group_id: 1,
    students: Students1,
  },
  {
    id: 4,
    name: "English",
    teacher: "Jane Doe",
    group_id: 1,
    students: Students2,
  },
  {
    id: 4,
    name: "English",
    teacher: "Jane Doe",
    group_id: 1,
    students: Students2,
  },
  {
    id: 1,
    name: "Math",
    teacher: "John Doe",
    group_id: 1,
    students: Students1,
  },
  {
    id: 2,
    name: "Science",
    teacher: "Jane Doe",
    group_id: 1,
    students: Students2,
  },
  {
    id: 3,
    name: "History",
    teacher: "John Doe",
    group_id: 1,
    students: Students1,
  },
  {
    id: 4,
    name: "English",
    teacher: "Jane Doe",
    group_id: 1,
    students: Students2,
  },
];
